const questionsDB = {
    math: [
        { q: "The sum of 24,520 + 3,578 is:", opts: ["27,998", "28,408", "28,098", "28,008"], ans: 2 },
        { q: "A driver traveled 100 km at 50 km/h, and the return trip took 3 hours. What is the average speed (km/h)?", opts: ["55", "40", "45", "50"], ans: 1 },
        { q: "A right-angled triangle has sides of 3 cm, 4 cm, and 5 cm. What is its area?", opts: ["12 cm²", "6 cm²", "5 cm²", "10 cm²"], ans: 1 },
        { q: "What is the result of 100.04 + 5.30 + 44.96?", opts: ["149.97", "150.03", "150.30", "149.30"], ans: 2 },
        { q: "A regular hexagon has a side length of 5 cm. What is its perimeter?", opts: ["15 cm", "25 cm", "30 cm", "28 cm"], ans: 2 },
        { q: "I saw a group of sheep on a farm. I counted 28 legs and 14 eyes. How many sheep were there?", opts: ["7", "14", "21", "42"], ans: 0 },
        { q: "Find the product of 2000 × 0.007:", opts: ["1.4", "14", "0.14", "140"], ans: 1 },
        { q: "Which number is ten thousand less than 453,762?", opts: ["453,662", "452,762", "443,762", "353,762"], ans: 2 },
        { q: "Divide 200 by 1/2 and add 20. The final result is:", opts: ["120", "220", "320", "420"], ans: 3 },
        { q: "Two sisters and two brothers will have a combined age of 100 in ten years. What will their combined age be in seven years?", opts: ["78", "88", "97", "Cannot be predicted"], ans: 1 },
        { q: "Mohammed worked 19 hours in Jan, 19 in Feb, and 22 in March. Total hours worked?", opts: ["40", "50", "60", "70"], ans: 2 },
        { q: "There are 2 roads from city A to B, and 3 from B to C. How many possible routes from A to C?", opts: ["2", "5", "6", "8"], ans: 2 },
        { q: "A room is 6m x 4m. If each floor tile covers 0.5 m², how many tiles are needed?", opts: ["24", "36", "41", "48"], ans: 3 },
        { q: "If half of a number is 18, what is one-third of that number?", opts: ["12", "14", "16", "18"], ans: 0 },
        { q: "The time now is 7:00 AM. What time will it be after 210 minutes?", opts: ["10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM"], ans: 1 }
    ],
    verbal: [
        { q: "Picture : Frame :: House : ?", opts: ["Wall", "Fence", "Door", "Roof"], ans: 1 },
        { q: "Day : ? :: 1 : 12", opts: ["Month", "Week", "Year", "Decade"], ans: 0 },
        { q: "Second floor is to First floor as:", opts: ["Egg is to Hen", "Sea is to Fish", "Bridge is to River", "Flowers are to Garden"], ans: 2 },
        { q: "Stadium is to Ball as:", opts: ["Scientist is to Lab", "Sea is to Fish", "Paper is to Book", "Sea is to Ship"], ans: 1 },
        { q: "A decade is:", opts: ["20 years", "30 years", "100 years", "10 years"], ans: 3 },
        { q: "Part to whole relationship -> Eyelid : Eye :: ?", opts: ["Nail : Finger", "Hand : Head", "Leg : Chest", "Nose : Mouth"], ans: 0 },
        { q: "Human : Breathing -> Life :: Flower : Thirst -> ?", opts: ["Plucking", "Color", "Uprooting", "Wilting"], ans: 3 },
        { q: "Mustafa planted cooking herbs like mint, basil, and dill. Thus, dill is used for:", opts: ["Preparing food", "Feeding sheep", "Decorating house", "Washing clothes"], ans: 0 },
        { q: "Wood is to Door as:", opts: ["Candy is to Sugar", "Key is to Handle", "Clay is to Brick", "Dress is to Fabric"], ans: 2 },
        { q: "Ship is to Sea as:", opts: ["Apple is to Seed", "Infant is to Cradle", "Pulp is to Banana", "Womb is to Fetus"], ans: 1 },
        { q: "The Arabic word 'Al-Watees' (الوطيس) historically means:", opts: ["Vessel", "War/Battle", "Boat", "Courtyard"], ans: 1 },
        { q: "Gutter is to Water as:", opts: ["Wind is to Window", "Chimney is to Smoke", "Pen is to Sharpener", "Canal is to Agriculture"], ans: 1 },
        { q: "Soldier is to Weapon as:", opts: ["Teacher is to Classroom", "Doctor is to Scalpel", "Sun is to Light", "Knowledge is to Ignorance"], ans: 1 },
        { q: "Hat is to Head as:", opts: ["School is to Classroom", "Pen is to Notebook", "Glasses are to Eyes", "Book is to Line"], ans: 2 },
        { q: "School is to Chalkboard as:", opts: ["Room is to House", "Garden is to Flower", "Classroom is to School", "Traffic light is to Street"], ans: 1 },
        { q: "Rug is to Prayer as:", opts: ["Playing is to Playground", "Bed is to Sleep", "Teacher is to Ruler", "Doctor is to Hospital"], ans: 1 },
        { q: "Carpenter is to Carpentry Shop as:", opts: ["Sword is to Spear", "Teacher is to Education", "Machine gun is to Tank", "Jeweler is to Workshop"], ans: 3 }
    ],
    science: [
        { q: "Which material allows electricity to pass between a battery and a light bulb?", opts: ["Copper wire", "Wooden rod", "Cotton thread", "Rubber tube"], ans: 0 },
        { q: "If a large pulley turns 1 revolution clockwise, a connected smaller pulley (1/3 radius) turns:", opts: ["1 rev clockwise", "2 revs counter-clockwise", "3 revs clockwise", "2 revs clockwise"], ans: 2 },
        { q: "If an escalator moves downwards, and a person walks upwards at the exact same speed, their position after 1 minute is:", opts: ["Moved upwards", "Remained in the same place", "Moved downwards", "Reached the top"], ans: 1 },
        { q: "Which direction of pulling a mass on a smooth surface requires the least force?", opts: ["Parallel to surface", "Angled upwards", "Angled downwards", "Vertical"], ans: 0 },
        { q: "Where do germs and viruses primarily exist?", opts: ["Air, food, water, skin cuts", "Polluted places", "Polluted food only", "Skin cuts only"], ans: 0 },
        { q: "Khalid went to the hospital with a fever. The doctor prescribed 'Fluot'. Therefore, 'Fluot' is for:", opts: ["Sterilization", "Prevention", "Treatment", "Cooking"], ans: 2 },
        { q: "If flour was petroleum, and water was used for life, flour would be used:", opts: ["For building", "In the closet", "As fuel", "In the house"], ans: 2 },
        { q: "If chickens hunt rabbits, and eagles are birds of prey, then chickens:", opts: ["Soar", "Are raised", "Prey", "Are domesticated"], ans: 2 }
    ],
    flexibility: [
        { q: "Which word is the odd one out?", opts: ["Triangle", "Hexagon", "Cube", "Pentagon"], ans: 2 },
        { q: "Barber is taller than Plumber and shorter than Tailor. Tailor is taller than Blacksmith. Blacksmith is shorter than Tailor and taller than Barber. Who is 3rd tallest?", opts: ["Barber", "Blacksmith", "Tailor", "Plumber"], ans: 0 },
        { q: "Hend scored higher than Hessa. Salwa scored higher than Souad. Hessa scored higher than Salwa. Who scored highest?", opts: ["Hend", "Hessa", "Salwa", "Souad"], ans: 0 },
        { q: "Which word is the odd one out?", opts: ["Mercy", "Hardness", "Tenderness", "Politeness"], ans: 1 },
        { q: "Peridot (Zabarjad) is a type of:", opts: ["Gemstone", "Bird", "Fish", "Wind"], ans: 0 },
        { q: "Special categories: Car -> ?", opts: ["Airplane", "Train", "Boat", "Submarine"], ans: 1 },
        { q: "Leopard : ?", opts: ["Deer", "Mouse", "Cheetah", "Rabbit"], ans: 2 },
        { q: "Abdullah is taller than Mohammed, who is shorter than Khalid and taller than Mahmoud. Who is the shortest?", opts: ["Abdullah", "Mohammed", "Khalid", "Mahmoud"], ans: 3 },
        { q: "If all birds bray and some dive, and all lions dive and some bray. We can conclude:", opts: ["All birds & lions dive", "Some lions bray & don't dive", "All birds bray & dive", "Some lions & all birds bray"], ans: 3 },
        { q: "All shapes are square. Every square has a middle hole. Some square things have handles. Therefore:", opts: ["All shapes have handles", "All shapes have a hole", "Every square has a handle", "Circular shapes have handles"], ans: 1 },
        { q: "Which word is the odd one out?", opts: ["Extravagance", "Rationalization", "Squandering", "Wasting"], ans: 1 },
        { q: "Mohammed graduated before Waleed. Waleed graduated after Zaid and before Ahmed. Who was the last to graduate?", opts: ["Mohammed", "Waleed", "Zaid", "Ahmed"], ans: 3 },
        { q: "Apple is to Orange as:", opts: ["Sun is to Day", "Cave is to Mountain", "Duck is to Chicken", "She-camel is to Camel"], ans: 2 },
        { q: "Low is to High as:", opts: ["Hungry is to Thirsty", "Moon is to Night", "Wealth is to Riches", "Few is to Many"], ans: 3 },
        { q: "'You are all from Adam, and Adam is from dust.' This implies people are:", opts: ["Cooperative", "Equal", "Gathered", "Different"], ans: 1 },
        { q: "If a dentist is a mechanic, and a captain is in a ship, a dentist is in a:", opts: ["Clinic", "Hospital", "Car", "Workshop"], ans: 3 },
        { q: "Tariq smelled a fragrant scent and heard chirping birds. He was likely in a:", opts: ["Perfume shop", "Beach", "Garden", "Flower shop"], ans: 2 },
        { q: "Which word is the odd one out?", opts: ["Family", "Battalion", "League", "Legion"], ans: 0 },
        { q: "Which word is the odd one out?", opts: ["Camphor", "Silk", "Ruby", "Amber"], ans: 2 }
    ]
};
